Revert^2 "Add Bluetooth extension HAL - CCO"
This reverts commit 3e78c36e5fc02c76ca0a59d17da7bdb6857ed005.

Reason for revert: build break
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix: 
    vendor.google.bluetooth_ext.IBluetoothCco/default (@1)

Bug: 361443653
Change-Id: I59f325ad1d8af5fca54cc9bb8a6208c5c8c20939